# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import nameNode_pb2 as nameNode__pb2


class Add2IndexStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.add_2_index = channel.unary_unary(
                '/name_node.Add2Index/add_2_index',
                request_serializer=nameNode__pb2.add2IndexRequest.SerializeToString,
                response_deserializer=nameNode__pb2.add2IndexResponse.FromString,
                )


class Add2IndexServicer(object):
    """Missing associated documentation comment in .proto file."""

    def add_2_index(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Add2IndexServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'add_2_index': grpc.unary_unary_rpc_method_handler(
                    servicer.add_2_index,
                    request_deserializer=nameNode__pb2.add2IndexRequest.FromString,
                    response_serializer=nameNode__pb2.add2IndexResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'name_node.Add2Index', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Add2Index(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def add_2_index(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/name_node.Add2Index/add_2_index',
            nameNode__pb2.add2IndexRequest.SerializeToString,
            nameNode__pb2.add2IndexResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
