# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FileServices.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x46ileServices.proto\x1a\x1bgoogle/protobuf/empty.proto\"=\n\x0c\x46ileMetadata\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04size\x18\x02 \x01(\x03\x12\x11\n\ttimestamp\x18\x03 \x01(\t\"+\n\x08\x46ileList\x12\x1f\n\x08metadata\x18\x01 \x03(\x0b\x32\r.FileMetadata\")\n\x0b\x46ileContent\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"\x1b\n\x0b\x46ileRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"0\n\x0fOperationStatus\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t2\xc0\x01\n\x0b\x46ileService\x12\x30\n\tListFiles\x12\x16.google.protobuf.Empty\x1a\t.FileList\"\x00\x12%\n\x08\x46indFile\x12\x0c.FileRequest\x1a\t.FileList\"\x00\x12-\n\x07PutFile\x12\x0c.FileContent\x1a\x10.OperationStatus\"\x00(\x01\x12)\n\x07GetFile\x12\x0c.FileRequest\x1a\x0c.FileContent\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FileServices_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_FILEMETADATA']._serialized_start=51
  _globals['_FILEMETADATA']._serialized_end=112
  _globals['_FILELIST']._serialized_start=114
  _globals['_FILELIST']._serialized_end=157
  _globals['_FILECONTENT']._serialized_start=159
  _globals['_FILECONTENT']._serialized_end=200
  _globals['_FILEREQUEST']._serialized_start=202
  _globals['_FILEREQUEST']._serialized_end=229
  _globals['_OPERATIONSTATUS']._serialized_start=231
  _globals['_OPERATIONSTATUS']._serialized_end=279
  _globals['_FILESERVICE']._serialized_start=282
  _globals['_FILESERVICE']._serialized_end=474
# @@protoc_insertion_point(module_scope)
