# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: list_files_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18list_files_service.proto\x12\nlist_files\"\x12\n\x10ListFilesRequest\"7\n\x11ListFilesResponse\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x05\x12\r\n\x05\x66iles\x18\x02 \x03(\t2`\n\x10ListFilesService\x12L\n\rmake_response\x12\x1c.list_files.ListFilesRequest\x1a\x1d.list_files.ListFilesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'list_files_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_LISTFILESREQUEST']._serialized_start=40
  _globals['_LISTFILESREQUEST']._serialized_end=58
  _globals['_LISTFILESRESPONSE']._serialized_start=60
  _globals['_LISTFILESRESPONSE']._serialized_end=115
  _globals['_LISTFILESSERVICE']._serialized_start=117
  _globals['_LISTFILESSERVICE']._serialized_end=213
# @@protoc_insertion_point(module_scope)
