# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import search_files_service_pb2 as search__files__service__pb2


class SearchFilesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.make_response = channel.unary_unary(
                '/search_files.SearchFiles/make_response',
                request_serializer=search__files__service__pb2.SearchFilesRequest.SerializeToString,
                response_deserializer=search__files__service__pb2.SearchFilesResponse.FromString,
                )


class SearchFilesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def make_response(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SearchFilesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'make_response': grpc.unary_unary_rpc_method_handler(
                    servicer.make_response,
                    request_deserializer=search__files__service__pb2.SearchFilesRequest.FromString,
                    response_serializer=search__files__service__pb2.SearchFilesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'search_files.SearchFiles', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SearchFiles(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def make_response(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/search_files.SearchFiles/make_response',
            search__files__service__pb2.SearchFilesRequest.SerializeToString,
            search__files__service__pb2.SearchFilesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
